# -*- coding: utf-8 -*-
"""Python challenge Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13p4RIskFuoMD95iOsmqVx0N3bGFmJoVQ

List
"""

names=["ABC","DEF","GHI"]
print(names)
names[1]="Hello"
print(names)
print(len(names))
print(names[0])
print(names[-1])
print(names[0:])
names=names+["JKL","23","90.5"]
names.append(input("Enter the values"))
print(names)

"""Allow duplicates"""

thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

"""type()"""

mylist = ["apple", "banana", "cherry"]
print(type(mylist))

"""The list() Constructor"""

thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

"""Range of Indexes"""

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])#The search will start at index 2 (included) and end at index 5 (not included).
print(thislist[:4])
print(thislist[2:])
print(thislist[-4:-1])

"""Check if Item Exists"""

thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")
alpha=["A","B","C"]
if "C" in alpha:
  print("Alpha is present")

"""Change a Range of Item Value"""

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)
thislist = ["apple", "banana", "cherry"]
thislist[1:2] = ["blackcurrant", "watermelon"]
print(thislist)#The length of the list will change when the number of items inserted does not match the number of items replaced.
thislist = ["apple", "banana", "cherry"]
thislist[1:3] = ["watermelon"]
print(thislist)
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

"""append()"""

thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

"""insert()"""

thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)