# -*- coding: utf-8 -*-
"""Python challenge Day 2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115zs9q7vz2K6vzmBviV5JSQvh0p22x6-
"""

num1=int(input())
num2=int(input())
num3=int(input())
sum=(num1+num2+num3)/3
print(sum)
print("Average is "+str(sum))

n1=int(input())
n2=int(input())
print("a: "+str(n1)+" b: "+str(n2))
t=n1
n1=n2
n2=t
print("a: "+str(n1)+" b: "+str(n2))

n1=input()
print(type(n1))

# symbol is used as comment h="""can also be used or assign"""

a="Hi how are you"
print(len(a))
print(a[4])#starts from 0 and white space is nincluded
print(a[4:8])
print(a[-1])
print(a[-1:-8])