# -*- coding: utf-8 -*-
"""Python challenge Day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cR5wbBgqp1bn6QoRhQkRY_4HXeMVO2Ox

Python basics
"""

print ('Hai')

print ("Hello")

a=10
b=5
print(a,b)

a=10
print("Hai "+str(a)+" Hello")

input("Enter a number")

a=input()
print(a)
b=input()
print(a+b)
sum=a+b
sum=int(a)+int(b)
print (sum)
print("Sum is" + str(sum))